### ISSUE TITLE
THIS ENGINE SHOULD BE WORKING AGAIN

### ISSUE THREAD

**Issue by MonadoBoy16** [KnightlessLabs/Platform-Fighter-Engine#2]
PLEASE RE-ADD THE GAMEMANAGER OPTION, BECAUSE IT DID NOT SHOW UP IN MY UNITY PROJECT!!!!

WHY DID YOU REMOVED IT????????

**Comment by MonadoBoy16** [comment]
YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YOU RUINED THE ENGINE, PLEASE FIX IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by christides11** [comment]
The GameManager still exist in the folder "PFE/Scripts/Core," however, with the start of the rewrite I put all the scripts in namespaces for proper organization.
I assume you mean that your scripts can't find it, which is because I've started putting scripts into namespaces for better organization. Any script that needs to reference the GameManager needs "using PFE.Core;" at the top, like so:

```
using PFE.Core;
public class ExampleClass : MonoBehavior {
    //....
}
```

Note that this framework is in a very early state, so changes like this may happen from time to time.

**Comment by MonadoBoy16** [comment]
But I get an error when I tried to put in in a scene

**Comment by christides11** [comment]
Make sure you check the Example's Prefab folder for how the GameManager should be setup, ignore the "GM" prefab in the main folder as I forgot to get rid of that one. Just in case I did break something with the GameManager though I'll upload the current project files in a second.

**Comment by MonadoBoy16** [comment]
When I look at the scripts, It says, "No MonoBehaviour"
